# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "mpt3sas" "xhci_pci" "ahci" "nvme" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ed74a661-77b4-4998-8076-d41f3ff443b3";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5650-B6C0";
      fsType = "vfat";
    };

  fileSystems."/filepit" =
    { device = "filepit";
      fsType = "zfs";
    };

  fileSystems."/filepit/music" =
    { device = "filepit/music";
      fsType = "zfs";
    };

  fileSystems."/filepit/videos" =
    { device = "filepit/videos";
      fsType = "zfs";
    };

  fileSystems."/filepit/pictures" =
    { device = "filepit/pictures";
      fsType = "zfs";
    };

  fileSystems."/filepit/documents" =
    { device = "filepit/documents";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/afe90d24-9e4e-4f32-9a17-998dd864c4cf"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
